adobe/node-httptransfer

- lib/util.js
- test/aemmultipart.test.js
Binary uploads were broken since https://github.com/adobe/node-httptransfer/commit/7ffed5a430a4dc764ee322f774b5b1b6a711e16f. Problem is that it started to treat all files as character files by setting `utf-8` encoding in `createReadStream()`.
- reverted previous changes to set `options` in `util.createReadStream()`
and `util.createWriteStream()` meant to fix Windows
- encoding: don't set as we treat all files as binary
- flags: was using the default values, can be left out
- mode: this only applies when files are created, defaults are fine (at least for unit tests here, including on Windows)
- string for options: never used in codebase
- added test `status-201-2urls binary`
> fix broken binary uploads by not setting "utf-8" encoding when reading file

- lib/aemmultipart.js
- test/aemmultipart.test.js
`maxPartSize` must be defined.
it will always choose `maxPartSize`. no more `options.partSize`, no more `minPartSize`
node 12
node 10
> multipart upload require maxPartSize

- lib/aemmultipart.js
- package-lock.json
- test/aemmultipart.test.js
Multipart upload was passing threw the incorrect value for max retry duration: `retryMax` instead of `retryMaxDuration`
retry params multipart upload passes in:
https://github.com/adobe/node-httptransfer/blob/master/lib/aemmultipart.js#L73 (see retryMax )
vs what the retry function looks at:
https://github.com/adobe/node-httptransfer/blob/master/lib/retry.js#L77 (retryMaxDuration)
Fixes # https://jira.corp.adobe.com/browse/NUI-919
> NUI-919 retryMaxDuration bug fix multipart upload

- lib/headers.js
These are not strictly neccesary because without a `return` the function result will be undefined, however it is confusing to leave them out.
> Add missing return values

- lib/filehandle.js
- lib/util.js
- test/util.test.js
Fixes a crash in the module when attempting to use Windows-style paths; for example: `C:\path\to\some\file.jpg`. The root of the issue was that converting the example path to a file URL would yield `file:///C:/path/to/some/file.jpg` (note the extra `/` in front of `C:`. When attempting to retrieve the path from the file URL, the module was getting `/C:/path/to/some/file.jpg`, which caused `fs.open()` to fail with a message similar to "Cannot find path C:\C:\path\to\some\file.jpg" (note the duplicated drive letter).
I updated the module so that it will strip off the leading `/` if the referenced path looks like a windows path. The criteria for "looking like a windows path" is "the value starts with a forward slash, followed by a single upper-case or lower-case letter, followed by a single …
> fix error when using windows-style file paths.

- lib/aemdownload.js
- lib/asset/transferasset.js
- lib/asset/transferpart.js
- lib/functions/transfer.js
- lib/functions/transferpartscreate.js
- lib/functions/transferpartsjoin.js
- lib/index.js
- lib/randomfileaccess.js
- lib/transfercontroller.js
- lib/util.js
- test/aemdownload.test.js
- test/util.test.js
The PR introduces `AEMDownload`, which is similar to `AEMUpload`, but in reverse. It allows fast transferring of files from a remote URL to a local file. It utilizes the HTTP `Content-Range` header to request parts of a remote file, which the module will concurrently transfer to a local file.
Open questions:
* Due to usage of `fs.write()` when writing parts to a local file, I had to convert the `Stream` provided in an HTTP response to a `Buffer` so it could be used with `fs.write()`. This reads the entirety of each `Stream` into memory. This is a risk to the amount of RAM the module will use while transferring files. However, since each chunk is (hopefully) small, and the number of concurrent threads is limited, this should reduce the risk. I also added a safety check to ensure that an …
> add aemdownload class for downloading assets.

- lib/asset/transferasset.js
- lib/filehandle.js
- lib/util.js
- test/asset/transferasset.test.js
- test/util.test.js
When working with Windows-style paths, the library was not providing valid paths in its file events. For example, when downloading a file the `filestart` event would look similar to the following:
```
{
fileName: 'my-asset.jpg',
fileSize: 100,
mimeType: 'image/jpeg',
targetFolder: '/C:/Users/someuser',
targetFile: '/C:/Users/someuser/my-asset.jpg',
sourceFolder: '/content/dam',
sourceFile: '/content/dam/my-asset.jpg',
}
```
Note the preceding forward slash, and the incorrect path separators. After this fix the event data will look as follows:
```
{
fileName: 'my-asset.jpg',
fileSize: 100,
mimeType: 'image/jpeg',
targetFolder: 'C:\Users\someuser',
targetFile: 'C:\Users\someuser\my-asset.jpg',
sourceFolder: '/content/dam',
sourceFile: '/content/dam/my-asset.jpg',
}
```
Note the correct …
> ensure file events contain valid windows paths.

- lib/aem/aemdownload.js
- lib/aem/aemupload.js
- lib/functions/aemcompleteupload.js
- lib/functions/aeminitiateupload.js
- lib/functions/getassetmetadata.js
- lib/functions/transfer.js
- lib/retry.js
- test/retry.test.js
Add the `retryMaxCount` option to retry a fixed number of attempts.
The option overrides `retryMaxDuration` when provided
> Add retryMaxCount, overrides retryMaxDuration if provided

- lib/asset/transferasset.js
- lib/functions/aemcompleteupload.js
- lib/functions/aeminitiateupload.js
- test/aem/aemupload.test.js
- test/functions/aemcompleteupload.test.js
- test/functions/aeminitiateupload.test.js
The key fix is that AEM provides the mimeType of the asset from the initiate upload servlet. This has to be passed along to when we invoke the complete upload servlet. This did not happen, resulting in a mimeType that was `"undefined"`.
In addition this PR adds missing and update test coverage that cover the bug.
> Fix mime-type handling in AEM uploads 

- lib/aem/aemupload.js
- lib/aem/upload-error.js
- lib/asset/asset.js
- lib/asset/transferasset.js
- lib/fetch.js
- lib/util.js
- package-lock.json
- package.json
- test/aem/aemupload.test.js
- test/aem/upload-error.test.js
- test/fetch.test.js
- test/util.test.js
Provides various changes to allow this module to be used in both a browser and Node.JS context:
* Refactor usage of `posix` from the `path` module, since it's not available when run in a browser.
* Support passing a `blob` option when uploading files with `AEMUpload`.
* Fix cases where the module was assuming the response body of a request would always be a stream; it's not a stream when running in a browser.
* Changed so that `window.fetch` is used instead of `node-fetch-npm` when running in a browser. `node-fetch-npm` was only designed to run in Node.JS, so it wasn't working correctly in this case.
Fixes #69 
- ~[ ] My change requires a change to the documentation.~
- ~[ ] I have updated the documentation accordingly.~
> fix issues when using module in a browser.

- lib/functions/aeminitiateupload.js
- test/functions/aeminitiateupload.test.js
The http transfer process is not expected to work on an AEM instance that is not configured with direct binary upload.
The library currently throw an error along the lines of `Error: 'files' field missing in initiateUpload response: [{"fileName”:”ascas-rasf-Pinouts.zip"}]`. This can be confusing to clients and doesn't provide helpful information about a known use case. This PR changes the error message to indicate that the target of the upload does not support direct binary upload.
> clarify error message when direct binary upload not enabled.

- e2e/aemtransfer.test.js
- e2e/e2eutils.js
- lib/functions/failunsupportedassets.js
- test/functions/failunsupportedassets.test.js
Updates the list of characters that are rejected by the module so that parenthesis are now allowed.
I also added a new e2e test that will verify that a single asset with invalid characters in its name doesn't fail the entire upload.
Fixes #76
> Allow parenthesis in asset names

- e2e/blocktransfer.test.js
- lib/aempartsize.js
- lib/block/blockupload.js
- lib/file.js
- lib/functions/transfer.js
- lib/index.js
- test/block/blockdownload.test.js
- test/block/blockupload.test.js
- test/file.test.js
- testbed/index.js
Goals:
- create `uploadFileConcurrently` to replace `uploadFile`
- create `uploadMultiPartFileConcurrently` to replace `uploadAEMMultipartFile`
- make sure all existing tests pass
- duplicate old `uploadFile` and  `uploadAEMMultipartFile` but using the concurrent versions
- most passed ootb but there is a small change in behavior with concurrent multipart:
- If a chunk fails, some or all (depending on concurrency vales) of the multipart chunk requests may be in progress. That is why I had to add nocks for those
- make sure they can be substituted 1:1 for the old functions
- tested with `npm link` in the asset-compute-pipeline
- changed upload functions to be the concurrent ones:
- replace `uploadFile` with  `uploadFileConcurrently`
-   replace `uploadAEMMultipartFile` with  ` …
> NUI-1674 refactor bulk upload and multipart upload api to adapt to asset-compute-pipeline use

- lib/csrf.js
- lib/functions/aemcompleteupload.js
- lib/functions/aeminitiateupload.js
- test/csrf.test.js
- test/functions/aemcompleteupload.test.js
- test/functions/aeminitiateupload.test.js
Request for CSRF before token AEMCompleteUpload and AEMInitiateUpload in browser.
This is tested together with `@adobe/aem-upload` package and an AppBuilder React App using `npm link`. 
Fixes # (CQ-4337713)
> CQ-4337713 Request for CSRF token before AEMCompleteUpload and AEMInitiateUpload

- package-lock.json
- package.json
Seems like mime-type package has been missing for long.
https://github.com/adobe/node-httptransfer/blob/b58d395f05e0a0d32835aae26af9f1076f440106/lib/functions/getassetmetadata.js#L22
Fixes General 
- [] I have added tests to cover my changes.
> install missing package mime-type

- lib/functions/transferpartscreate.js
- test/file-concurrently.test.js
Now it will show how many transfer parts are created (chunks to be downloaded) per request:
```
5 transfer parts created (target uses file protocol)
```
This is important to track in logs since we are changing the preferred part sizes.
Also added some download tests with multiple parts and a retry test for 503s and etimedout. I am unable to reproduce the issue here: https://jira.corp.adobe.com/browse/ASSETS-4407
related to tickets: https://jira.corp.adobe.com/browse/ASSETS-211, https://jira.corp.adobe.com/browse/ASSETS-4407
> [ASSETS-4407][ASSETS-211] add better logging on the amount of chunks created per request, add retry on chunks tests

- lib/functions/aeminitiateupload.js
- test/functions/aeminitiateupload.test.js
As described in the linked issue, it appears that AEM may have multiple ways of responding when direct binary upload isn't enabled. This PR modifies the library's logic that reports when direct binary upload isn't enabled to handle these cases.
Fixes #145
> BUGFIX-RELEASE: correctly report when direct binary upload is not enabled

- package-lock.json
- package.json
Reverts the `semantic-release` package version update to remain compatible with CI version of NodeJS 14; `semantic-release` > v17 requires NodeJS 18.
Semantic Release error: https://github.com/adobe/node-httptransfer/actions/runs/5158246477/jobs/9291712655
Recent PR with packages updates: https://github.com/adobe/node-httptransfer/pull/147
Fixes # ASSETS-24927
> Reverting Semantic Release version to work with Node 14

- .releaserc.json
The release of my previous commit failed with the message:
```
Failed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
An error occurred while running semantic-release: TypeError: Cannot read properties of undefined (reading 'parserOpts')
```
I updated to the latest version of semantic release and some of its plugins. Upon reviewing the commit-analyzer documentation, it appears that it needs a `parserOpts` value in its custom configuration. This PR adds that.
> add missing semantic release config option

- README.md
- lib/aem/createassetservletrequestgenerator.js
- lib/block/blockdownload.js
- lib/block/blockupload.js
- lib/functions/getassetmetadata.js
- lib/functions/transfer.js
- lib/functions/transferpartscreate.js
- lib/randomfileaccess.js
Intended to close #160 to avoid log pollution in downstream apps.
Only imported the already existing logger and replaced all `console.log` with `logger.info` (in the `lib` directory).
Fixes #160
> avoid console.log
